// # this file is ignored from .nuxtignore

export const SET_DATA_CONTEXT = 'SET_DATA_CONTEXT'

// spinners
export const ENABLE_SPINNER = 'ENABLE_SPINNER'
export const DISABLE_SPINNER = 'DISABLE_SPINNER'

// context
export const ADD_ITEM_CONTEXT = 'ADD_ITEM_CONTEXT'

// polygons
export const SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS = 'SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS'
export const SET_ACTIVE_VISIBLE_POLYGON_BUTTON = 'SET_ACTIVE_VISIBLE_POLYGON_BUTTON'
