// # this file is ignored from .nuxtignore

export const SET_DATA_CONTEXT = 'SET_DATA_CONTEXT'

// spinners
export const ENABLE_SPINNER = 'ENABLE_SPINNER'
export const DISABLE_SPINNER = 'DISABLE_SPINNER'

// satelital indexes
export const SET_SELECTED_SATELITAL_INDEX = 'SET_SELECTED_SATELITAL_INDEX'
export const SET_SIDE_BY_SIDE_VISIBLE = 'SET_SIDE_BY_SIDE_VISIBLE'
export const SET_LAYER_SATELITAL_INDEX = 'SET_LAYER_SATELITAL_INDEX'

// context
export const ADD_ITEM_CONTEXT = 'ADD_ITEM_CONTEXT'

// polygons
export const SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS = 'SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS'
export const SET_ACTIVE_VISIBLE_POLYGON_BUTTON = 'SET_ACTIVE_VISIBLE_POLYGON_BUTTON'
