// # this file is ignored from .nuxtignore

// context
export const ADD_ITEM_CONTEXT = 'ADD_ITEM_CONTEXT'
export const SET_DATA_CONTEXT = 'SET_DATA_CONTEXT'
export const SET_ITEM_CONTEXT = 'SET_ITEM_CONTEXT'

// spinners
export const ENABLE_SPINNER = 'ENABLE_SPINNER'
export const DISABLE_SPINNER = 'DISABLE_SPINNER'
export const SPINNERS = {
  PROCESSING_FORM: 'PROCESSING_FORM',
  LOADING_DRAWER: 'LOADING_DRAWER',
  LOADING_PAGE: 'LOADING_PAGE'
}

// satelital indexes
export const SET_SELECTED_SATELITAL_INDEX = 'SET_SELECTED_SATELITAL_INDEX'
export const SET_SIDE_BY_SIDE_VISIBLE = 'SET_SIDE_BY_SIDE_VISIBLE'
export const SET_LAYER_SATELITAL_INDEX = 'SET_LAYER_SATELITAL_INDEX'

// polygons
export const SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS = 'SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS'
export const SET_ACTIVE_VISIBLE_POLYGON_BUTTON = 'SET_ACTIVE_VISIBLE_POLYGON_BUTTON'

// satelital images
export const SET_SATELITAL_IMAGES_FILTERED = 'SET_SATELITAL_IMAGES_FILTERED'

//layers
export const TOGGLE_VISIBLE_LAYER = 'TOGGLE_VISIBLE_LAYER'
