export const SERVICES = {
  AUTH: {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT'
  },

  LEAFLET: {
    FIND_LAYER: 'FIND_LAYER',
    DELETE_LAYER: 'DELETE_LAYER',
    ADD_LAYER: 'ADD_LAYER',
    GET_LAYERS: 'GET_LAYERS',
    GET_LAYERS_IDS: 'GET_LAYERS_IDS',
    SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS: 'SET_ACTIVE_VISIBLE_POLYGONS_BUTTONS'
  }
}
